seed: 42
device: auto  # auto, cpu, cuda, mps
output_dir: output/${now:%Y%m%d_%H%M%S}  # carpeta unica para logs, plots y checkpoints

dataset:
  name: folder  # mnist, fashion_mnist, cifar10, cifar100, folder
  root: ./data
  path: ./dataset  # usado solo si name: folder
  class_names: []  # usado solo si name: folder. Ejemplo: ["gato", "perro"]
  download: true
  image_size: 
  batch_size: 
  num_workers: 
  num_folds: 
  fold_index: 0  # 0, 1, 2, 3 o 4

training:
  epochs: 
  optimizer: 
  learning_rate: 
  weight_decay: 0.0
  betas: [0.0, 0.0]  # usado solo por adam

eval:
# TODO: agregar ruta a checkpoint *.pt para evaluar un modelo entrenado o para predict
# e.g. output/20260704_112353/checkpoints/best.pt
  checkpoint_path: null

hydra:
  run:
    dir: ${output_dir}
  job:
    chdir: false
